# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  PENTAHOTAG: master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
    - name: Set current date as env variable
      run: |
        echo "PACKAGE7ZFILE=${{ github.run_id }}.7z" >> $GITHUB_ENV
        echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    - name: Package 
      run: 7z a ${{ env.PACKAGE7ZFILE }} ./ -mx=0 -v1000m
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PACKAGE7ZFILE }}*
        tag_name: ${{ env.PENTAHOTAG }}_${{ env.MY_DATE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
